name: Merge develop with main
on:
  push:
    branches:
      - main
jobs:
  merge-develo-with-main:
    runs-on: ubuntu-latest
    steps:
      - uses: dequelabs/action-sync-branches@v1
        with:
          head: main
          base: develop
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-title: 'chore: merge master into develop'
          pr-labels: chore
